name: Build and Push Docker container image

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  TARGET_PROJECT: c57ee7
  TARGET_ENV: dev
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker application image
      run: docker compose build
      working-directory: ./applications/Unity.GrantManager
    - name: Connect to OpenShift API
      run: |
        oc login --token=$AUTH_TOKEN --server=$CLUSTER
        oc project $TARGET_PROJECT-$TARGET_ENV
        oc registry login
    - name: push to application image to OpenShift Container Registry
      run:  | 
        docker tag unity-grantmanager-web image-registry.apps.silver.devops.gov.bc.ca/$TARGET_PROJECT-$TARGET_ENV/unity-grantmanager-web:latest
        docker push image-registry.apps.silver.devops.gov.bc.ca/$TARGET_PROJECT-$TARGET_ENV/unity-grantmanager-web:latest
      
