name: Dev - Build & Push docker images

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'database/**'
      - 'documentation/**'
      - 'openshift/**'
      - 'tests/**'
      - 'CODE_OF_CONDUCT.md'
      - 'COMPLIANCE.yaml'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'SECURITY..md'
    
env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.OPENSHIFT_TOKEN_DEV }}
  TARGET_PROJECT: ${{ vars.PROJECT_NAMESPACE }}
  TARGET_ENV: ${{ vars.NAME }} 
  ART_REPO_USER: ${{ secrets.ARTIFACTORY_USER_DEV }}
  ART_REPO_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN_DEV }}

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4
    - name: Build application Docker images
      run: docker compose build
      working-directory: ./applications
    - name: Connect to JFrog Artifactory
      run: |
        docker login --username $ART_REPO_USER --password $ART_REPO_TOKEN artifacts.developer.gov.bc.ca
    - name: Push application images to Artifactory container registry
      run:  | 
        docker tag dotnetapp image-registry.apps.silver.devops.gov.bc.ca/$TARGET_PROJECT-$TARGET_ENV/dotnetapp:github-latest
        # docker push image-registry.apps.silver.devops.gov.bc.ca/$TARGET_PROJECT-$TARGET_ENV/dotnetapp:github-latest
    - name: Connect to OpenShift API
      run: |
        oc login --token=$AUTH_TOKEN --server=$CLUSTER
        oc project $TARGET_PROJECT-$TARGET_ENV
        oc registry login
    - name: Push application images to OpenShift container registry
      run:  | 
        docker tag dotnetapp image-registry.apps.silver.devops.gov.bc.ca/$TARGET_PROJECT-$TARGET_ENV/dotnetapp:github-latest
        # docker push image-registry.apps.silver.devops.gov.bc.ca/$TARGET_PROJECT-$TARGET_ENV/dotnetapp:github-latest
      
      
