name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ./applications
    - name: Connect to OpenShift API
      run: |
        oc login --token=$AUTH_TOKEN --server=$CLUSTER
        oc project c57ee7-dev
        oc get is 
    - name: push to OpenShift Container Registry
      run:  docker push my-image-name:$(date +%s)
      
