# Create PR into main from selected branch or tag
name: Patch - Hotfix create PR

on:
  workflow_dispatch:
    inputs:
      pr_base:
        description: 'Hotfix - base: branch'
        default: 'main'
        required: true
        type: string
      pr_title:
        description: 'Hotfix - Title for the pull request'
        default: 'Hotfix to Main Release'
        required: true
        type: string
env:
  TARGET_ENV: ${{ inputs.pr_base }}
  GH_TOKEN: ${{secrets.GH_API_TOKEN}}

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.pr_base }}
    steps:
    - name: Get variables
      run: |
        echo "target=$TARGET_ENV "
        echo "base=$GITHUB_REF_NAME"
        echo "Environment: $TARGET_ENV OC_TARGET_PROJECT=$OC_TARGET_PROJECT"
        echo "Environment: $TARGET_ENV JFROG_REPO_PATH=$JFROG_REPO_PATH"
        echo "..."
        env | sort
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install GitHub CLI
      #   run: sudo apt-get install gh -y

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          gh pr create --base ${{ inputs.pr_base }} --head ${{ github.ref }} --title "${{ inputs.pr_title }}" --body "This is a new hotfix PR"
