# Create PR into main from selected branch or tag
name: Patch - Hotfix create PR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Hotfix - compare: branch'
        default: 'dev'
        required: true
        type: string
      pr_title:
        description: 'Hotfix - Title for the pull request'
        default: 'Hotfix to Main Release: yyyy-mm-dd'
        required: true
        type: string
jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: ${{ github.ref }}
          destination: main
          title: ${{ github.event.inputs.pr_title }}
          body: ${{ github.event.inputs.pr_body }}
          branch: hotfix-pr-${{ github.ref }}
