# This is a basic workflow that is manually triggered

name: Workflow - Run manual trigger

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Environment'
        # Default value if no value is explicitly provided
        default: 'dev'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
env:
  TARGET_ENV: ${{ vars.NAME }} 
  OC_CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  OC_AUTH_TOKEN: ${{ secrets.OPENSHIFT_TOKEN_DEV }}
  OC_TARGET_PROJECT: ${{ vars.PROJECT_NAMESPACE }}
  JFROG_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  JFROG_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  JFROG_REPO_PATH: ${{ vars.ARTIFACTORY_REPO_DEV }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send message
      run: echo "Environment = ${{ inputs.name }}, $TARGET_ENV"

  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.name }}
    steps:
    - uses: actions/checkout@v4
    - name: Build dotnetapp docker images
      run: docker compose build
      working-directory: ./applications/dotnetapp
    - name: Build aspnetapp docker images
      run: docker compose build
      working-directory: ./applications/aspnetapp
    - name: Connect to JFrog Artifactory
      run: |
        docker login --username $JFROG_USERNAME --password $JFROG_PASSWORD artifacts.developer.gov.bc.ca
    - name: Push application images to Artifactory container registry
      run:  | 
        docker tag dotnetapp artifacts.developer.gov.bc.ca/$JFROG_REPO_PATH/dotnetapp
        docker push artifacts.developer.gov.bc.ca/$JFROG_REPO_PATH/dotnetapp
        docker tag aspnetapp artifacts.developer.gov.bc.ca/$JFROG_REPO_PATH/aspnetapp
        docker push artifacts.developer.gov.bc.ca/$JFROG_REPO_PATH/aspnetapp
    - name: Connect to OpenShift API
      run: |
        # oc login --token=$AUTH_TOKEN --server=$CLUSTER
        # oc project $TARGET_PROJECT-$TARGET_ENV
        # oc registry login
    - name: Push application images to OpenShift container registry
      run:  | 
        # docker tag dotnetapp image-registry.apps.silver.devops.gov.bc.ca/$TARGET_PROJECT-$TARGET_ENV/dotnetapp:github-latest
        # docker push image-registry.apps.silver.devops.gov.bc.ca/$TARGET_PROJECT-$TARGET_ENV/dotnetapp:github-latest
      
      
