name: Main - Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != 'test' ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]]; then
            echo ""
            echo "Error: Pull Request into main must come from a merged 'test' or 'hotfix/*' branch"
            echo "Quick Fix: Cancel this PR rename the source branch and try again or target into dev branch."
            exit 1
          fi