name: Change feature or bugfix PR base into dev

on:
  pull_request:
    types: [opened]
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  change-base-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Change base branch to dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO/pulls/$PR_NUMBER \
          -d '{"base":"dev"}'
