name: Branch Protection Rules

on:
  pull_request:
    branches:
      - dev

jobs:
  check-dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} =~ ^feature/ ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^bugfix/ ]]; then
            echo ""
            echo "Error: Pull Request into dev should come from a merged 'feature/*', 'hotfix/*', or 'bugfix/*' branch"
            echo "Quick Fix: Edit the PR rename source branch and try again."
            exit 0
          fi