name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != 'test' ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]]; then
            echo ""
            echo "Error: Pull request must come from 'test' or 'hotfix/' branch"
            echo "Fix: Edit the PR into base: or rename source branch and try again."
            exit 1
          fi